services:
  - name: learnforge-fe
    type: web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist/spa
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_CLERK_PUBLISHABLE_KEY
        value: pk_test_YXdhaXRlZC1oYWdmaXNoLTgwMDMuY2xlcmsuYWNjb3VudHMuZGV2JA
